### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by BerkeDiler** [brandon3055/PI-Docs#28]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-06-19 13:31:46 EET
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
    at com.brandon3055.projectintelligence.docmanagement.LanguageManager.mcLanguage(LanguageManager.java:402)
    at com.brandon3055.projectintelligence.docmanagement.LanguageManager.getUserLanguage(LanguageManager.java:378)
    at com.brandon3055.projectintelligence.docmanagement.LanguageManager.getModLanguage(LanguageManager.java:309)
    at com.brandon3055.projectintelligence.docmanagement.LanguageManager.getPageLanguage(LanguageManager.java:290)
    at com.brandon3055.projectintelligence.docmanagement.DocumentationPage.getLocalizationLang(DocumentationPage.java:107)
    at com.brandon3055.projectintelligence.docmanagement.DocumentationPage.getMarkdownFile(DocumentationPage.java:134)
    at com.brandon3055.projectintelligence.docmanagement.DocumentationPage.getMarkdownLines(DocumentationPage.java:144)
    at com.brandon3055.projectintelligence.client.gui.PIGuiOverlay$DocElement.reloadDoc(PIGuiOverlay.java:342)
    at com.brandon3055.projectintelligence.client.gui.PIGuiOverlay$DocElement.reloadElement(PIGuiOverlay.java:322)
    at com.brandon3055.projectintelligence.client.gui.PIGuiOverlay$DocElement.updateBounds(PIGuiOverlay.java:525)
    at com.brandon3055.projectintelligence.client.gui.PIGuiOverlay$DocElement.addChildElements(PIGuiOverlay.java:276)
    at com.brandon3055.brandonscore.client.gui.modulargui.GuiElementManager.add(GuiElementManager.java:82)
    at com.brandon3055.projectintelligence.client.gui.PIGuiOverlay.addElements(PIGuiOverlay.java:84)
    at com.brandon3055.brandonscore.client.gui.modulargui.GuiElementManager.onGuiInit(GuiElementManager.java:41)
    at com.brandon3055.projectintelligence.client.gui.PIGuiOverlay.onGuiInit(PIGuiOverlay.java:74)
    at com.brandon3055.projectintelligence.client.gui.PIGuiOverlay.<init>(PIGuiOverlay.java:66)
    at com.brandon3055.projectintelligence.client.gui.GuiInGuiRenderer.guiInit(GuiInGuiRenderer.java:41)
    at com.brandon3055.projectintelligence.client.GuiEventHandler.onGuiInit(GuiEventHandler.java:39)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2686_GuiEventHandler_onGuiInit_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:480)
    at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:1018)
    at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:501)
    at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:322)
    at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:112)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
    at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:50)
    at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.lambda$channelRead0$0(OpenGuiHandler.java:43)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more

Help me with this crash error

**Comment by FoxMcloud5655** [comment]
This is the wrong repository.  Report your issue in the PI repo, not the PI-Docs repo.
